version: 2.1
jobs:

  test:
    docker:
      - image: 'cimg/node:14.14.0'
    steps:
      - run: npm ci
      - run: npm test


  keepwarm:
    triggers:
      - schedule:
          cron: "0 */29 * * *"
    docker:
      - image: 'cimg/node:14.14.0'
    steps:
      - run: echo "hello world"
      - run: curl -fL "https://hackernews-podcast.herokuapp.com/_keepwarm"
